# Generated by Django 3.2.6 on 2021-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210821_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='audio_file',
            field=models.FileField(default='', upload_to='audio/', verbose_name='Аудиозапись'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcript',
            name='video_file',
            field=models.FileField(upload_to='video/', verbose_name='Видеозапись'),
        ),
    ]
