# Generated by Django 3.2.6 on 2021-08-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transcript_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудиозапись'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
