# Generated by Django 3.2.6 on 2021-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerole',
            options={'verbose_name': 'Роль сотрудника', 'verbose_name_plural': 'Роли сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeerolesinmeeting',
            options={'verbose_name': 'Роль сотрудника на совещании', 'verbose_name_plural': 'Роли сотрудников на совещании'},
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, max_length=190, null=True, verbose_name='Должность'),
        ),
    ]
