# Generated by Django 3.2.6 on 2021-08-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartitionTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('start_time', models.FloatField(verbose_name='Начало отрывка')),
                ('end_time', models.FloatField(verbose_name='Конец отрывка')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='core.transcript', verbose_name='Стенограмма')),
            ],
        ),
    ]
