# Generated by Django 3.2.6 on 2021-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_partitiontranscript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partitiontranscript',
            options={'verbose_name': 'Фрагмент стенограммы', 'verbose_name_plural': 'Фрагменты стенограмм'},
        ),
        migrations.AlterField(
            model_name='employeerolesinmeeting',
            name='role',
            field=models.IntegerField(default=0, verbose_name='Роль'),
        ),
    ]
