# Generated by Django 3.2.6 on 2021-08-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210822_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
    ]
