# Generated by Django 3.2.6 on 2021-08-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_employeerole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitiontranscript',
            name='transcript',
        ),
        migrations.AddField(
            model_name='meeting',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудиозапись'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Стенограмма'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Видеозапись'),
        ),
        migrations.AddField(
            model_name='partitiontranscript',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='core.meeting', verbose_name='Совещание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeerolesinmeeting',
            name='role',
            field=models.IntegerField(choices=[(0, 'Присутвующий'), (1, 'Секретарь'), (2, 'Председательствующий')], default=0, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Получение аудио'), (1, 'Получение текста'), (2, 'Готово'), (3, 'На согласовании')], default=0),
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
