# Generated by Django 3.2.6 on 2021-08-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210822_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Решение', 'verbose_name_plural': 'Решения'},
        ),
        migrations.AddField(
            model_name='meeting',
            name='audio_file_mp3',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудиозапись в MP3'),
        ),
    ]
