# Generated by Django 3.2.6 on 2021-08-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210822_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerolesinmeeting',
            name='report_read',
            field=models.BooleanField(default=False, verbose_name='Ознакомлен'),
        ),
        migrations.AddField(
            model_name='employeerolesinmeeting',
            name='report_send',
            field=models.BooleanField(default=False, verbose_name='Протокол отрпавлен'),
        ),
    ]
