# Generated by Django 3.2.6 on 2021-08-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210822_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerolesinmeeting',
            name='report_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на протокол'),
        ),
    ]
